-- AULA 8 - FUNCOES E AGRUPAMENTO
--AVG - MÉDIA
SELECT
    ROUND(AVG(SALARY),2) FUNC_AVG
    FROM EMPLOYEES;
    
-- TRAZER MÉDIA SALARIAL DE CADA DEPARTAMENTO
SELECT
    D.DEPARTMENT_NAME, 
    ROUND(AVG(E.SALARY),2) MEDIA_SALARIAL
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME;

-- COUNT - CONTAGEM
SELECT
    COUNT(EMPLOYEE_ID) "FUNCIONÁRIOS ATIVOS"
    FROM EMPLOYEES;

-- CONTAR QUANTOS FUNCIONARIOS EXISTEM EM CADA DEPARTAMENTO
SELECT
    DEPARTMENT_NAME,
    COUNT(EMPLOYEE_ID)
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    GROUP BY DEPARTMENT_NAME
    ORDER BY 1;
    
-- MAX - MAIOR VALOR
SELECT 
    MAX(SALARY) "MAIOR SALÁRIO"
    FROM EMPLOYEES;

-- QUAL O MAIOR SALARIO DE CADA DEPARTAMENTO
SELECT
    D.DEPARTMENT_NAME,
    MAX(E.SALARY) "MAIOR SALARIO"
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME
    ORDER BY 1;

-- MIN - MENOR VALOR DE UM GRUPO
SELECT
    MIN(SALARY) "MENOR SALARIO"
    FROM EMPLOYEES;
    
-- TRAZER O MENOR SALARIO DE CADA DEPARTAMENTO
SELECT
    D.DEPARTMENT_NAME,
    MIN(E.SALARY) "MENOR SALÁRIO",
    MAX(E.SALARY) "MAIOR SALÁRIO"
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME
    ORDER BY 1;

-- SOMA 
SELECT
    SUM(SALARY) "SOMA DE TODOS OS SALARIOS"
    FROM EMPLOYEES;
    
-- SOMA DE SALARIOS POR DEPARTAMENTO
SELECT
    D.DEPARTMENT_NAME,
    SUM(E.SALARY) "SOMA DE SALÁRIOS"
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME
    ORDER BY 2;

-- DESVIO PADRAO
SELECT
    STDDEV(SALARY) "DESVIO PADRÃO GERAL"
    FROM EMPLOYEES;
    
-- DESVIO PADRAO POR DEPARTAMENTO
SELECT
    D.DEPARTMENT_NAME,
    STDDEV(E.SALARY) "DESVIO PADRAO"
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME;

-- VARIANCIA
SELECT 
    VARIANCE(SALARY) "VARIANCIA GERAL"
    FROM EMPLOYEES;

-- VARIANCIA DE SALARIO POR DEPARTAMENTO
SELECT
    D.DEPARTMENT_NAME,
    ROUND(VARIANCE(E.SALARY),2) "VARIANCIA"
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME
    ORDER BY 2;
    
-- CLAUSULA HAVING
SELECT
    D.DEPARTMENT_NAME,
    COUNT(E.EMPLOYEE_ID) QTD_FUNC
    FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME
    HAVING COUNT(E.EMPLOYEE_ID) >= 2
    ORDER BY 2;
    
SELECT * FROM LIVROS;    

SELECT
    COD_LIVROS,
    NOME_LIVRO,
    CASE
        WHEN NOME_LIVRO IS NULL
        THEN 'Registro incompleto'
        ELSE 'Registro OK'
    END STATUS_LIVRO
FROM LIVROS;   

/* MOSTRA SE O FUNCIONARIO POSSUI PERCENTUAL DE COMISSAO CASO A COLUNA
 COMMISSION_PCT POSSUA ALGUM VALOR*/
SELECT
    FIRST_NAME,
    CASE
        WHEN COMMISSION_PCT IS NULL
        THEN 'NÃO É VENDEDOR'
        ELSE 'VENDEDOR'
    END STATUS_COMISSAO
FROM EMPLOYEES;    

SELECT * FROM EMPLOYEES;